Fix test failure with spies to not cause other tests to fail
It would cause the error message:

    TypeError: Attempted to wrap trigger which is already wrapped